### **Importing Libraries and the Dataset**

In [ ]:
# Mounting the drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
# Used to ignore the warning given as output of the code
import warnings
warnings.filterwarnings('ignore')

# Basic libraries of python for numeric and dataframe computations
import numpy as np
import pandas as pd

# Basic library for data visualization
import matplotlib.pyplot as plt

# Slightly advanced library for data visualization
import seaborn as sns

# To compute the cosine similarity between two vectors
from sklearn.metrics.pairwise import cosine_similarity

# Simple Linear Regression

#Load function from sklearn
from sklearn import linear_model

# A dictionary output that does not raise a key error
from collections import defaultdict

# A performance metrics in sklearn
from sklearn.metrics import mean_squared_error

from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn import metrics

from sklearn import metrics
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report

from sklearn.model_selection import train_test_split

### **Load the dataset**

In [ ]:
pd.set_option('display.max_columns', None)

In [ ]:
pd.set_option('display.max_rows', None)

In [ ]:
def data_preprocessing_2(df_with_path, chosen_columns):
  df = pd.read_csv(df_with_path)

  ndf = df[chosen_columns]

  # numerical_features = X.select_dtypes(include=['int64', 'float64']).columns
  # categorical_features = X.select_dtypes(include=['object']).columns

  ndf_cat = ndf.select_dtypes(include=['object']).columns

  # One hot encoding for ndf_cat

  ndf = pd.get_dummies(ndf, columns=ndf_cat)

  return ndf

In [ ]:
# first set of columns I am going to run models on
df_set_1 = ['Arr_Delay_At_Least_15_Minutes','Carrier_Name', 'Quarter', 'Month', 'Week_Day','Dep_Time_Block_Group', 'Scheduled_Departure_Time','Distance_Group' ]

In [ ]:
df = data_preprocessing_2('/content/drive/MyDrive/Flight_On_Time_Data.csv',df_set_1)

In [ ]:
df.shape

(6777978, 44)

In [ ]:
df.columns

Index(['Arr_Delay_At_Least_15_Minutes', 'Quarter', 'Scheduled_Departure_Time',
       'Distance_Group', 'Carrier_Name_Alaska Airlines Inc.',
       'Carrier_Name_Allegiant Air', 'Carrier_Name_American Airlines Inc.',
       'Carrier_Name_Delta Air Lines Inc.', 'Carrier_Name_Endeavor Air Inc.',
       'Carrier_Name_Envoy Air', 'Carrier_Name_Frontier Airlines Inc.',
       'Carrier_Name_Hawaiian Airlines Inc.', 'Carrier_Name_JetBlue Airways',
       'Carrier_Name_PSA Airlines Inc.', 'Carrier_Name_Republic Airline',
       'Carrier_Name_SkyWest Airlines Inc.',
       'Carrier_Name_Southwest Airlines Co.', 'Carrier_Name_Spirit Air Lines',
       'Carrier_Name_United Air Lines Inc.', 'Month_Apr', 'Month_Aug',
       'Month_Dec', 'Month_Feb', 'Month_Jan', 'Month_Jul', 'Month_Jun',
       'Month_Mar', 'Month_May', 'Month_Nov', 'Month_Oct', 'Month_Sep',
       'Week_Day_Friday', 'Week_Day_Monday', 'Week_Day_Saturday',
       'Week_Day_Sunday', 'Week_Day_Thursday', 'Week_Day_Tuesday',
       'W

In [ ]:
# X = df.drop(['Arr_Delay_At_Least_15_Minutes'], axis=1)
# y = df['Arr_Delay_At_Least_15_Minutes']

# X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=78978)


Here are Machine Leanirng models I would like to

In [ ]:
#X = df.drop(['Arr_Delay_At_Least_15_Minutes'], axis=1)
#y = df['Arr_Delay_At_Least_15_Minutes']

Xfeat = df.drop(['Arr_Delay_At_Least_15_Minutes'], axis=1).columns

In [ ]:
# need to work more on this function
# the idea is to give input data, predicting feature and different sets of features (x and Y)
# and also different models with different parameters (like Logistic regression model, knn, SVC etc)
# depending on the parameters we'll get different accracy of the model, precision and recall (and f1)
# we can save al lthat data then and choose the best model and the best features for given dataset


# def best_model(data, features, yf, test_size_p, model_p, model_params):

def best_model(data, features, yf, test_size_p, model_p):

  X = data[features]
  y = data[yf]

  X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=test_size_p, random_state=78978)

  # LogisticRegression(C=1e9)
  # KNeighborsClassifier(n_neighbors=9)
  # DecisionTreeClassifier()
  # RandomForestClassifier()
  # GradientBoostingClassifier(random_state=78978)
  # SVC(random_state=78978)
  # GaussianNB()

  model = model_p
  model.fit(X_train, y_train)

  y_pred = model.predict(X_test)
  print(metrics.accuracy_score(y_test, y_pred))
  print (metrics.precision_score(y_test, y_pred))
  print (metrics.recall_score(y_test, y_pred))
  print (metrics.f1_score(y_test, y_pred))


  accur = metrics.accuracy_score(y_test, y_pred)
  prec = metrics.precision_score(y_test, y_pred)
  rec = metrics.recall_score(y_test, y_pred)
  f1 = metrics.recall_score(y_test, y_pred)
  roc_auc = metrics.roc_auc_score(y_test, y_pred)

  metrics_vec = [model_p, accur, prec,rec, f1, roc_auc]

  print(metrics.classification_report(y_test, y_pred))
  print(metrics.confusion_matrix(y_test, y_pred))
  print("Accuracy: ")
  print(accur)
  print("Precision: ")
  print(prec)
  print("Recall: ")
  print(rec)
  print("F1: ")
  print(f1)
  print("ROC AUC: ")
  print(roc_auc)

  return metrics_vec


* LogisticRegression(C=1e9)
* KNeighborsClassifier(n_neighbors=9)
* DecisionTreeClassifier()
* RandomForestClassifier()
* GradientBoostingClassifier(random_state=78978)
* SVC(random_state=78978)
* GaussianNB()


In [ ]:
# I tred to run all the models in look but it didn't work
models_to_run = [LogisticRegression(C=1e9), DecisionTreeClassifier(), RandomForestClassifier(), GradientBoostingClassifier(random_state=78978), SVC(random_state=78978), GaussianNB(),KNeighborsClassifier(n_neighbors=3)]


In [ ]:
best_model(df,Xfeat,'Arr_Delay_At_Least_15_Minutes',0.2, GaussianNB())

In [ ]:
best_model(df,Xfeat,'Arr_Delay_At_Least_15_Minutes',0.4, GaussianNB())

0.684361712486611
0.313231971414574
0.4679580080400839
0.37527211882558553
              precision    recall  f1-score   support

           0       0.85      0.74      0.79   2161944
           1       0.31      0.47      0.38    549248

    accuracy                           0.68   2711192
   macro avg       0.58      0.60      0.58   2711192
weighted avg       0.74      0.68      0.71   2711192

[[1598411  563533]
 [ 292223  257025]]
[GaussianNB(), 0.684361712486611, 0.313231971414574, 0.4679580080400839, 0.4679580080400839, 0.6036488474572448]


[GaussianNB(),
 0.684361712486611,
 0.313231971414574,
 0.4679580080400839,
 0.4679580080400839,
 0.6036488474572448]

In [ ]:
# I tred to run all the models in look but it didn't work
m_res = []
for m in models_to_run:
  print(m)
  m_res. append(best_model(df,Xfeat,'Arr_Delay_At_Least_15_Minutes',0.25, m))

LogisticRegression(C=1000000000.0)
0.7978642604433769
0.5799438990182328
0.00963223946655796
0.018949744224280647
              precision    recall  f1-score   support

           0       0.80      1.00      0.89   1351065
           1       0.58      0.01      0.02    343430

    accuracy                           0.80   1694495
   macro avg       0.69      0.50      0.45   1694495
weighted avg       0.75      0.80      0.71   1694495

[[1348669    2396]
 [ 340122    3308]]
[LogisticRegression(C=1000000000.0), 0.7978642604433769, 0.5799438990182328, 0.00963223946655796, 0.00963223946655796, 0.5039294118398764]
DecisionTreeClassifier()
0.7698470635794146
0.356943155773213
0.1691465509710858
0.22952626868679288
              precision    recall  f1-score   support

           0       0.81      0.92      0.86   1351065
           1       0.36      0.17      0.23    343430

    accuracy                           0.77   1694495
   macro avg       0.59      0.55      0.55   1694495
weighted

In [ ]:
best_model(df,Xfeat,'Arr_Delay_At_Least_15_Minutes',0.4, GradientBoostingClassifier())

0.7984631851967695
0.6084866061207357
0.014516211256117455
0.028355955622022543
              precision    recall  f1-score   support

           0       0.80      1.00      0.89   2161944
           1       0.61      0.01      0.03    549248

    accuracy                           0.80   2711192
   macro avg       0.70      0.51      0.46   2711192
weighted avg       0.76      0.80      0.71   2711192

[[2156814    5130]
 [ 541275    7973]]
[GradientBoostingClassifier(), 0.7984631851967695, 0.6084866061207357, 0.014516211256117455, 0.014516211256117455, 0.5060716734170486]


[GradientBoostingClassifier(),
 0.7984631851967695,
 0.6084866061207357,
 0.014516211256117455,
 0.014516211256117455,
 0.5060716734170486]

In [ ]:
best_model(df,Xfeat,'Arr_Delay_At_Least_15_Minutes',0.4, SVC())

In [ ]:
best_model(df,Xfeat,'Arr_Delay_At_Least_15_Minutes',0.4, KNeighborsClassifier(n_neighbors=3))

In [ ]:
############################################################################################

In [ ]:
X = df.drop(['Arr_Delay_At_Least_15_Minutes'], axis=1)
y = df['Arr_Delay_At_Least_15_Minutes']

#X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=78978)

In [ ]:
from xgboost import XGBClassifier

xgb_clf = XGBClassifier(use_label_encoder=False)
xgb_clf.fit(X_train, y_train)

y_pred = xgb_clf.predict(X_test)

print("Accuracy: ")
print (metrics.accuracy_score(y_test, y_pred))

print("F1: ")
print (metrics.f1_score(y_test, y_pred))

print("Precision: ")
print (metrics.precision_score(y_test, y_pred))

print("Recall: ")
print (metrics.recall_score(y_test, y_pred))

print("ROC AUC: ")
print (metrics.roc_auc_score(y_test, y_pred))

print("Confusion matrix: ")
print (metrics.confusion_matrix(y_test, y_pred))


print(classification_report(y_test, y_pred))

Accuracy: 
0.8003409570402982
F1: 
0.10474820143884893
Precision: 
0.5716039132161294
Recall: 
0.057657014681892334
ROC AUC: 
0.5233394659966746
Confusion matrix: 
[[2138210   23734]
 [ 517580   31668]]
              precision    recall  f1-score   support

           0       0.81      0.99      0.89   2161944
           1       0.57      0.06      0.10    549248

    accuracy                           0.80   2711192
   macro avg       0.69      0.52      0.50   2711192
weighted avg       0.76      0.80      0.73   2711192



In [ ]:
# XGBoost Classifier Hyperparameter Tuning

from scipy import stats
from sklearn.model_selection import RandomizedSearchCV

param_grid = dict(
    n_estimators=stats.randint(10, 1000),
    max_depth=stats.randint(1, 10),
    learning_rate=stats.uniform(0, 1)
)

xgb_clf = XGBClassifier(use_label_encoder=False)
xgb_cv = RandomizedSearchCV(
    xgb_clf, param_grid, cv=5, n_iter=150,
    scoring='accuracy', n_jobs=-1, verbose=1
)
xgb_cv.fit(X_train, y_train)
best_params = xgb_cv.best_params_
print(f"Best paramters: {best_params}")

xgb_clf = XGBClassifier(**best_params)
xgb_clf.fit(X_train, y_train)

Fitting 5 folds for each of 150 candidates, totalling 750 fits


In [ ]:
y_pred = xgb_clf.predict(X_test)

print("Accuracy: ")
print (metrics.accuracy_score(y_test, y_pred))

print("F1: ")
print (metrics.f1_score(y_test, y_pred))

print("Precision: ")
print (metrics.precision_score(y_test, y_pred))

print("Recall: ")
print (metrics.recall_score(y_test, y_pred))

print("ROC AUC: ")
print (metrics.roc_auc_score(y_test, y_pred))

print("Confusion matrix: ")
print (metrics.confusion_matrix(y_test, y_pred))


print(classification_report(y_test, y_pred))

In [ ]:
#######################################################

In [ ]:
#####. Best model so far was Naive Bayes


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=78978)

In [ ]:
gnb = GaussianNB()
gnb.fit(X_train, y_train)

# Predict and evaluate
y_pred = gnb.predict(X_test)

# Predict and evaluate
y_pred = gnb.predict(X_test)

print("Accuracy: ")
print (metrics.accuracy_score(y_test, y_pred_class))

print("F1: ")
print (metrics.f1_score(y_test, y_pred_class))

print("Precision: ")
print (metrics.precision_score(y_test, y_pred_class))

print("Recall: ")
print (metrics.recall_score(y_test, y_pred_class))

print("ROC AUC: ")
print (metrics.roc_auc_score(y_test, y_pred_class))

print("Confusion matrix: ")
print (metrics.confusion_matrix(y_test, y_pred_class))

print(classification_report(y_test, y_pred))

In [ ]:
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import GridSearchCV

param_grid_nb = {
    'var_smoothing': np.logspace(0,-9, num=100)
}

nbModel_grid = GridSearchCV(estimator=GaussianNB(), param_grid=param_grid_nb, verbose=1, cv=10, n_jobs=-1)
nbModel_grid.fit(X_train, y_train)
print(nbModel_grid.best_estimator_)


In [ ]:
##############################################

################################################################################

**1) Logistic regression**

In [ ]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression(C=1e9)
logreg.fit(X_train, y_train)

#log_reg = Pipeline(steps=[('preprocessor', preprocessor),
#                           ('classifier', LogisticRegression(random_state=78978))])

LogisticRegression(C=1000000000.0)

In [ ]:
y_pred_class = logreg.predict(X_test)
from sklearn import metrics

print("Accuracy: ")
print (metrics.accuracy_score(y_test, y_pred_class))

print("F1: ")
print (metrics.f1_score(y_test, y_pred_class))

print("Precision: ")
print (metrics.precision_score(y_test, y_pred_class))

print("Recall: ")
print (metrics.recall_score(y_test, y_pred_class))

print("ROC AUC: ")
print (metrics.roc_auc_score(y_test, y_pred_class))

print("Confusion matrix: ")
print (metrics.confusion_matrix(y_test, y_pred_class))

Accuracy: 
0.7974994024768441
F1: 
0.0033836647412694553
Precision: 
0.5703794369645043
Recall: 
0.0016968655325099045
ROC AUC: 
0.5006860788847483
Confusion matrix: 
[[2161242     702]
 [ 548316     932]]


In [ ]:
metrics.confusion_matrix(y_test, y_pred_class)

array([[2161242,     702],
       [ 548316,     932]])

In [ ]:
pd.crosstab(y_test, y_pred_class, rownames=['True'], colnames=['Predicted'], margins=True)

Predicted        0     1      All
True                             
0          2161242   702  2161944
1           548316   932   549248
All        2709558  1634  2711192

**2) KNN**

In [ ]:
# different model

## Before scaling
knn = KNeighborsClassifier(n_neighbors=9)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)

print("Accuracy: ")
print (metrics.accuracy_score(y_test, y_pred))

print("F1: ")
print (metrics.f1_score(y_test, y_pred))

print("Precision: ")
print (metrics.precision_score(y_test, y_pred))

print("Recall: ")
print (metrics.recall_score(y_test, y_pred))

print("ROC AUC: ")
print (metrics.roc_auc_score(y_test, y_pred))

print("Confusion matrix: ")
print (metrics.confusion_matrix(y_test, y_pred))


print(classification_report(y_test, y_pred))

**3) Decision Tree**

In [ ]:
from sklearn.tree import DecisionTreeClassifier

# Create and fit the model
tree_clf = DecisionTreeClassifier()
tree_clf.fit(X_train, y_train)

# Predict and evaluate
y_pred = tree_clf.predict(X_test)

print("Accuracy: ")
print (metrics.accuracy_score(y_test, y_pred))

print("F1: ")
print (metrics.f1_score(y_test, y_pred))

print("Precision: ")
print (metrics.precision_score(y_test, y_pred))

print("Recall: ")
print (metrics.recall_score(y_test, y_pred))

print("ROC AUC: ")
print (metrics.roc_auc_score(y_test, y_pred))

print("Confusion matrix: ")
print (metrics.confusion_matrix(y_test, y_pred))


print(metrics.classification_report(y_test, y_pred))

Accuracy: 
0.7646241948191054
F1: 
0.23357525722679073
Precision: 
0.3431433783960223
Recall: 
0.1770438854579352
ROC AUC: 
0.5454722615161333
Confusion matrix: 
[[1975802  186142]
 [ 452007   97241]]


NameError: name 'classification_report' is not defined

In [ ]:

print(metrics.classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.81      0.91      0.86   2161944
           1       0.34      0.18      0.23    549248

    accuracy                           0.76   2711192
   macro avg       0.58      0.55      0.55   2711192
weighted avg       0.72      0.76      0.73   2711192



**4)Random Forest**

In [ ]:
from sklearn.ensemble import RandomForestClassifier

# Create and fit the model
forest_clf = RandomForestClassifier()
forest_clf.fit(X_train, y_train)

# Predict and evaluate
y_pred = forest_clf.predict(X_test)


print("Accuracy: ")
print (metrics.accuracy_score(y_test, y_pred_class))

print("F1: ")
print (metrics.f1_score(y_test, y_pred_class))

print("Precision: ")
print (metrics.precision_score(y_test, y_pred_class))

print("Recall: ")
print (metrics.recall_score(y_test, y_pred_class))

print("ROC AUC: ")
print (metrics.roc_auc_score(y_test, y_pred_class))

print("Confusion matrix: ")
print (metrics.confusion_matrix(y_test, y_pred_class))

print(classification_report(y_test, y_pred))



**5)Gradient Boosting**

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier

# Create and fit the model
gb_clf = GradientBoostingClassifier(random_state=78978)
gb_clf.fit(X_train, y_train)

# Predict and evaluate
y_pred = gb_clf.predict(X_test)


print("Accuracy: ")
print (metrics.accuracy_score(y_test, y_pred_class))

print("F1: ")
print (metrics.f1_score(y_test, y_pred_class))

print("Precision: ")
print (metrics.precision_score(y_test, y_pred_class))

print("Recall: ")
print (metrics.recall_score(y_test, y_pred_class))

print("ROC AUC: ")
print (metrics.roc_auc_score(y_test, y_pred_class))

print("Confusion matrix: ")
print (metrics.confusion_matrix(y_test, y_pred_class))

print(classification_report(y_test, y_pred))

**6) Support Vector**

In [ ]:
from sklearn.svm import SVC

# Create and fit the model
svc_clf = SVC(random_state=78978)
svc_clf.fit(X_train, y_train)

# Predict and evaluate
y_pred = svc_clf.predict(X_test)

print("Accuracy: ")
print (metrics.accuracy_score(y_test, y_pred_class))

print("F1: ")
print (metrics.f1_score(y_test, y_pred_class))

print("Precision: ")
print (metrics.precision_score(y_test, y_pred_class))

print("Recall: ")
print (metrics.recall_score(y_test, y_pred_class))

print("ROC AUC: ")
print (metrics.roc_auc_score(y_test, y_pred_class))

print("Confusion matrix: ")
print (metrics.confusion_matrix(y_test, y_pred_class))

print(classification_report(y_test, y_pred))

**7) Gaussian Naive Bayes**

In [ ]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train, y_train)

# Predict and evaluate
y_pred = gnb.predict(X_test)

# Predict and evaluate
y_pred = gnb.predict(X_test)

print("Accuracy: ")
print (metrics.accuracy_score(y_test, y_pred_class))

print("F1: ")
print (metrics.f1_score(y_test, y_pred_class))

print("Precision: ")
print (metrics.precision_score(y_test, y_pred_class))

print("Recall: ")
print (metrics.recall_score(y_test, y_pred_class))

print("ROC AUC: ")
print (metrics.roc_auc_score(y_test, y_pred_class))

print("Confusion matrix: ")
print (metrics.confusion_matrix(y_test, y_pred_class))

print(classification_report(y_test, y_pred))

In [ ]:
# need to work more on this function
# the idea is to give input data, predicting feature and different sets of features (x and Y)
# and also different models with different parameters (like Logistic regression model, knn, SVC etc)
# depending on the parameters we'll get different accracy of the model, precision and recall (and f1)
# we can save al lthat data then and choose the best model and the best features for given dataset


# def best_model(data, features, yf, test_size_p, model_p, model_params):

def best_model(data, features, yf, test_size_p, model_p):

  X = data[features]
  y = data[yf]

  X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=test_size_p, random_state=78978)

  # LogisticRegression(C=1e9)
  # KNeighborsClassifier(n_neighbors=9)
  # DecisionTreeClassifier()
  # RandomForestClassifier()
  # GradientBoostingClassifier(random_state=78978)
  # SVC(random_state=78978)
  # GaussianNB()

  model = model_p
  model.fit(X_train, y_train)

  y_pred = model.predict(X_test)
  print(metrics.accuracy_score(y_test, y_pred))
  print (metrics.precision_score(y_test, y_pred))
  print (metrics.recall_score(y_test, y_pred))
  print (metrics.f1_score(y_test, y_pred))


  accur = metrics.accuracy_score(y_test, y_pred)
  prec = metrics.precision_score(y_test, y_pred)
  rec = metrics.recall_score(y_test, y_pred)
  f1 = metrics.recall_score(y_test, y_pred)
  roc_auc = metrics.roc_auc_score(y_test, y_pred)

  metrics_vec = [accur, prec,rec, f1, metrics_vec]

  print(metrics.classification_report(y_test, y_pred))
  print(metrics.confusion_matrix(y_test, y_pred))

  return metrics_vec


In [ ]:
#X = df.drop(['Arr_Delay_At_Least_15_Minutes'], axis=1)
#y = df['Arr_Delay_At_Least_15_Minutes']

Xfeat = df.drop(['Arr_Delay_At_Least_15_Minutes'], axis=1).columns

In [ ]:
best_model(df,Xfeat,'Arr_Delay_At_Least_15_Minutes',0.4, GaussianNB())

NameError: name 'GaussianNB' is not defined

In [ ]:
best_model()